- apps/rave-mark/frontend/src/index.tsx
https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis
> chore(rave-mark): use React 18 API for app setup

- apps/rave-mark/backend/schema.sql
- apps/rave-mark/backend/src/app.ts
- apps/rave-mark/backend/src/store.ts
- apps/rave-mark/frontend/src/api.ts
- apps/rave-mark/frontend/src/screens/voter_flow_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/done_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/index.tsx
- apps/rave-mark/frontend/src/screens/voting/print_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/review_onscreen_ballot_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/review_printed_ballot_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/start_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/submit_screen.tsx
- move the PIN check to the end; we don't actually need it to start voting, only to sign the CVR
- improve UI & styling
- add more explanation and context
- print the ballot first, then review printed ballot, then cast the digital ballot
https://github.com/votingworks/rave/assets/1938/86a569ff-2392-431d-9984-317a79f9fd96
Manual
> feat(rave-mark): various improvements to the voter flow

- script/rave-setup
We need it for printing the mailing labels.
n/a
Manual
> build: add `chromium` to build script

- Cargo.lock
- libs/auth-rs/Cargo.toml
This should have been part of #60.
> build(auth-rs): add missing dependencies

- apps/cacvote-jx-terminal/backend/db/migrations/20240226180624_add-return-address-to-elections.down.sql
- apps/cacvote-jx-terminal/backend/db/migrations/20240226180624_add-return-address-to-elections.sql
- apps/cacvote-jx-terminal/backend/src/app.rs
- apps/cacvote-jx-terminal/backend/src/db.rs
- apps/cacvote-jx-terminal/frontend/src/pages/elections_page.rs
- apps/cacvote-scan/backend/db/migrations/20240226180624_add-return-address-to-elections.down.sql
- apps/cacvote-scan/backend/db/migrations/20240226180624_add-return-address-to-elections.sql
- apps/cacvote-scan/backend/src/db.rs
- libs/types-rs/src/cacvote/client/input.rs
- libs/types-rs/src/cacvote/client/output.rs
- libs/types-rs/src/cacvote/jx/mod.rs
- services/cacvote-server/db/migrations/20240226180624_add-return-address-to-elections.down.sql
- services/cacvote-server/db/migrations/20240226180624_add-return-address-to-elections.sql
- services/cacvote-server/src/app.rs
- services/cacvote-server/src/db.rs
- services/cacvote-server/src/usability_testing.rs
This is hardcoded for now. We'll add a form for it later.
> feat: adds a free-form ballot return address to elections

- libs/types-rs/src/cacvote/mod.rs
- services/cacvote-server/bin/create-object.rs
- services/cacvote-server/db/migrations/20240305194646_objects.sql
- services/cacvote-server/src/app.rs
- services/cacvote-server/src/client.rs
- services/cacvote-server/src/db.rs
> fix: rename `certificate` to `certificates` as it's likely to be a chain

- apps/cacvote-mark/backend/package.json
- apps/cacvote-mark/backend/schema.sql
- apps/cacvote-mark/backend/src/cacvote-server/client.ts
- apps/cacvote-mark/backend/src/cacvote-server/types.ts
- apps/cacvote-mark/backend/src/server.ts
- apps/cacvote-mark/backend/src/store.ts
- libs/db/src/client.test.ts
- libs/db/src/client.ts
- libs/grout/package.json
- libs/types-rs/src/cacvote/mod.rs
- pnpm-lock.yaml
- vxsuite.code-workspace
Duplicates the Rust client in TypeScript.
> feat(mark): sync journal entries from `cacvote-server`

- apps/cacvote-jx-terminal/backend/src/db.rs
- apps/cacvote-mark/backend/src/app.ts
- apps/cacvote-mark/backend/src/cacvote-server/client.test.ts
- apps/cacvote-mark/backend/src/cacvote-server/sync.test.ts
- apps/cacvote-mark/backend/src/cacvote-server/sync.ts
- apps/cacvote-mark/backend/src/cacvote-server/types.ts
- apps/cacvote-mark/backend/src/store.test.ts
- apps/cacvote-mark/backend/src/store.ts
- apps/cacvote-mark/frontend/src/api.ts
- apps/cacvote-mark/frontend/src/screens/registration/start_screen.tsx
- libs/types-rs/src/cacvote/mod.rs
- services/cacvote-server/bin/get-object-by-id.rs
- services/cacvote-server/src/client.rs
- services/cacvote-server/src/db.rs
Allows generating a registration request on CACVote Mark and syncing it to the server.
> Support Registration Requests

- Cargo.lock
- apps/cacvote-jx-terminal/backend/src/smartcard.rs
- libs/auth-rs/Cargo.toml
- libs/auth-rs/examples/check_pin.rs
- libs/auth-rs/examples/verify.rs
- libs/auth-rs/examples/verify_signature.rs
- libs/auth-rs/src/card_command.rs
- libs/auth-rs/src/card_details.rs
- libs/auth-rs/src/card_reader.rs
- libs/auth-rs/src/lib.rs
- libs/auth-rs/src/tlv.rs
- libs/auth-rs/src/vx_card.rs
- make `Tlv` use more explicit methods instead of `TryFrom`
- add docs to `Tlv`
- add signing capability
- add new struct `VxCard` for managing a smartcard interactions rather than going through `CardReader`
- add various "example" binaries for testing things out
> feat(auth-rs): make a bunch of improvements to smartcard auth

- libs/auth-rs/src/card_command.rs
- libs/auth-rs/src/card_details.rs
- libs/auth-rs/src/tlv.rs
- libs/auth-rs/src/vx_card.rs
> feat(auth-rs): add card sign function

- apps/cacvote-jx-terminal/backend/.env
- apps/cacvote-jx-terminal/backend/src/app.rs
- apps/cacvote-jx-terminal/backend/src/config.rs
- apps/cacvote-jx-terminal/backend/src/sync.rs
- apps/cacvote-mark/backend/src/app.ts
- apps/cacvote-mark/backend/src/bin/create-object/main.ts
- apps/cacvote-mark/backend/src/cacvote-server/client.ts
- apps/cacvote-mark/backend/src/cacvote-server/sync.test.ts
- apps/cacvote-mark/backend/src/cacvote-server/sync.ts
- apps/cacvote-mark/backend/src/cacvote-server/types.test.ts
- apps/cacvote-mark/backend/src/cacvote-server/types.ts
- apps/cacvote-mark/backend/src/store.test.ts
- apps/cacvote-mark/backend/src/store.ts
- libs/types-rs/src/cacvote/mod.rs
- services/cacvote-server/bin/get-journal-entries.rs
- services/cacvote-server/src/app.rs
- services/cacvote-server/src/client.rs
- services/cacvote-server/src/db.rs
The serialization scheme got out of sync between the two sides. This brings them back in line. Also ensures that the card used to authenticate with JX terminal is the expected one. This will change once we use the TPM.
> various improvements to JX/Mark interop

- apps/cacvote-jx-terminal/backend/src/app.rs
- apps/cacvote-jx-terminal/backend/src/db.rs
- apps/cacvote-jx-terminal/frontend/public/styles.css
- apps/cacvote-jx-terminal/frontend/src/layouts/app_layout.rs
- apps/cacvote-jx-terminal/frontend/src/pages/ballots_page.rs
- apps/cacvote-jx-terminal/frontend/src/pages/voters_page.rs
- apps/cacvote-mark/backend/src/app.ts
- apps/cacvote-mark/backend/src/cacvote-server/client.ts
- apps/cacvote-mark/backend/src/cacvote-server/types.ts
- apps/cacvote-mark/backend/src/server.ts
- libs/types-rs/src/cacvote/mod.rs
- libs/types-rs/src/cdf/cvr.rs
- services/cacvote-server/src/db.rs
https://github.com/votingworks/cacvote/assets/1938/7d36ed89-7883-4b86-b35a-7ae3df92be5f
> feat: add support for casting ballots

- apps/cacvote-jx-terminal/frontend/src/components/create_election_modal.tsx
- apps/cacvote-jx-terminal/frontend/src/components/generate_encrypted_tally_modal.test.tsx
- apps/cacvote-jx-terminal/frontend/src/components/generate_encrypted_tally_modal.tsx
- apps/cacvote-jx-terminal/frontend/src/screens/tally_screen.tsx
- apps/cacvote-jx-terminal/frontend/src/use_modal_keybindings.tsx
The buttons don't do anything yet.
Manually.
> feat(jx): add buttons to Tally Screen

- apps/cacvote-jx-terminal/backend/src/app.rs
- apps/cacvote-jx-terminal/backend/src/db.rs
- apps/cacvote-jx-terminal/frontend/src/api.ts
- apps/cacvote-jx-terminal/frontend/src/cacvote-server/session_data.ts
- apps/cacvote-jx-terminal/frontend/src/cacvote-server/types.ts
- apps/cacvote-jx-terminal/frontend/src/components/generate_encrypted_tally_modal.test.tsx
- apps/cacvote-jx-terminal/frontend/src/components/generate_encrypted_tally_modal.tsx
- apps/cacvote-jx-terminal/frontend/src/screens/tally_screen.tsx
- apps/cacvote-jx-terminal/frontend/src/utils/download.ts
- libs/types-rs/src/cacvote/mod.rs
- libs/ui/src/icons.tsx
Hooks up the frontend UI to the backend EG tally functions.
https://github.com/votingworks/cacvote/assets/1938/34b2dac8-cf45-49c5-b010-fac7636ce1de
Manual. Added a tiny bit of automated testing.
> feat(jx): hook up tally & decrypt features on Tally screen

- .sqlx/query-150c905080cb7f3444a4fd653f3f659003db969c6fd3426749986f7399e26d7d.json
- .sqlx/query-41b8c5ce19e9ffbb0daac85090c32b82b7694f504d198e74fc809b1b9fc86a8f.json
- .sqlx/query-c60de1aa793fcf38f93c37c4106397cc41d2fc6f06b85960472c129ce9f5da05.json
- .sqlx/query-e88b276bfb8c27720fe8c91bac2dcf44999b2b4c7d48f0ed0940e7a2b44e6138.json
- apps/cacvote-jx-terminal/backend/src/app.rs
- apps/cacvote-jx-terminal/backend/src/db.rs
- apps/cacvote-jx-terminal/frontend/src/api.ts
- apps/cacvote-jx-terminal/frontend/src/cacvote-server/session_data.ts
- apps/cacvote-jx-terminal/frontend/src/screens/tally_screen.tsx
- libs/electionguard-rs/src/ballot.rs
- libs/electionguard-rs/src/config.rs
- libs/electionguard-rs/src/lib.rs
- libs/electionguard-rs/src/mixnet.rs
- libs/electionguard-rs/src/zip.rs
- libs/types-rs/src/cacvote/mod.rs
- libs/ui/src/icons.tsx
https://github.com/votingworks/cacvote/assets/1938/9b95e996-0a94-462b-9f17-52875df3fe59
> feat(jx): add support for ElectionGuard mixnet shuffling

- README.md
- script/cacvote-setup
Also adds docs for configuring the `EG_CLASSPATH` variable.
> build: setup `egk-ec-mixnet` during setup

- apps/cacvote-server/backend/src/app.rs
- apps/cacvote-server/backend/src/db.rs
- apps/cacvote-server/frontend/src/api.ts
- apps/cacvote-server/frontend/src/app_root.tsx
- apps/cacvote-server/frontend/src/screens/actions_screen.tsx
- apps/cacvote-server/frontend/src/screens/search_screen.tsx
Returns all cast ballots and scanned mail labels for a given CAC ID.
> feat(cacvote-server): add "Search by CAC ID"

- libs/auth/scripts/program-development-system-administrator-java-card-without-vx-admin
- libs/auth/scripts/program_development_system_administrator_java_card_without_vx_admin.ts
- libs/auth/scripts/utils.ts
- libs/auth/src/certs.ts
- libs/auth/src/java_card.ts
Updated for dev instead of prod since that's what I need right now.
> feat(auth): port sysadmin card programming script from `vxsuite`

- apps/cacvote-jx-terminal/backend/bin/decrypt-tally.rs
- apps/cacvote-jx-terminal/backend/src/sync.rs
- apps/cacvote-server/backend/bin/cacvote-client.rs
- libs/cacvote-server-client/src/signer.rs
Don't hardcode use of the TPM as that's not great for dev.
> fix(jx): use the `SIGNER` config value

- libs/electionguard/package.json
This PR includes architecture specific files used by electionguard.
> include the arch specific files

- apps/cacvote-jx-terminal/backend/src/session_manager.rs
Adds a 100ms interval for checking that the authenticated session data has changed. I'd prefer this to be event-driven, but this is fine for now.
> fix(jx-terminal): refresh UI on changes

- README.md
- apps/cacvote-jx-terminal/backend/.env
- apps/cacvote-jx-terminal/backend/src/config.rs
- apps/cacvote-jx-terminal/backend/src/db.rs
- apps/cacvote-jx-terminal/backend/src/sync.rs
- apps/cacvote-mark/backend/.env
- apps/cacvote-mark/backend/src/cacvote-server/client.ts
- apps/cacvote-mark/backend/src/cacvote-server/mock_object.ts
- apps/cacvote-mark/backend/src/cacvote-server/sync.ts
- apps/cacvote-mark/backend/src/cacvote-server/types.ts
- apps/cacvote-mark/backend/src/cacvote-server/usability_test_client.ts
- apps/cacvote-mark/backend/src/env.d.ts
- apps/cacvote-mark/backend/src/globals.ts
- apps/cacvote-mark/backend/src/server.ts
- apps/cacvote-server/backend/.env
- apps/cacvote-server/backend/bin/cacvote-server.rs
- apps/cacvote-server/backend/bin/enroll-voter-terminal-machine.rs
- apps/cacvote-server/backend/src/app.rs
- apps/cacvote-server/backend/src/client.rs
- apps/cacvote-server/backend/src/config.rs
- apps/cacvote-server/backend/src/db.rs
- apps/cacvote-server/backend/src/state.rs
- libs/types-rs/src/cacvote/mod.rs
This will require setting the machine cert (in prod, the TPM's signed public key) and CAC CAs properly.
> fix: verify certificates in objects against the proper CA

- apps/cacvote-jx-terminal/backend/src/config.rs
These were causing build errors.
> build(jx): fix field visibility

- RustConfig
Missed the RustConfig setting.
> set SQLX_OFFLINE to false

- RustConfig
- apps/cacvote-server/backend/script/build
Reverting after the sqlx query cache was refreshed.
> revert SQLX_OFFLINE change

- Procfile
Passing cert path to heroku server
> pass prod cert to server

- libs/cacvote-server-client/src/signer.rs
We weren't quite handling stdio correctly when shelling out to `openssl`.
> fix(jx): make TPM signing work

- libs/usb-drive/src/mocks/memory_usb_drive.ts
- libs/usb-drive/src/usb_drive.ts
https://votingworks.slack.com/archives/C04HWTEFUSG/p1728393601873379
> fix(usb-drive): add missing function

- apps/cacvote-mark/backend/src/app.ts
Use the dimensions that work on Debian.
> update label printer dimensions
