votingworks/cacvote

- apps/mark/frontend/src/apimachine_config.test.tsx
- apps/mark/frontend/src/app.test.tsx
- apps/mark/frontend/src/app_card_unhappy_paths.test.tsx
- apps/mark/frontend/src/app_cardless_voting.test.tsx
- apps/mark/frontend/src/app_contest_candidate_no_party.test.tsx
- apps/mark/frontend/src/app_contest_ms_either_neither.test.tsx
- apps/mark/frontend/src/app_contest_multi_seat.test.tsx
- apps/mark/frontend/src/app_contest_single_seat.test.tsx
- apps/mark/frontend/src/app_contest_write_in.test.tsx
- apps/mark/frontend/src/app_contest_yes_no.test.tsx
- apps/mark/frontend/src/app_data.test.tsx
- apps/mark/frontend/src/app_polls_flows.test.tsx
- apps/mark/frontend/src/app_quit_on_idle.test.tsx
- apps/mark/frontend/src/app_replace_election.test.tsx
- apps/mark/frontend/src/app_root.tsx
- apps/mark/frontend/src/app_setup_errors.test.tsx
- apps/mark/frontend/src/app_test_mode.test.tsx
- apps/mark/frontend/src/lib/gamepad.test.tsx
- apps/mark/frontend/src/pages/unconfigured_election_screen_wrapper.tsx
- apps/mark/frontend/test/helpers/election.ts
We should be using the backend as the data store for everything.
```
tree ~/.config/kiosk-browser/data
/home/vx/.config/kiosk-browser/data
└── state.json
0 directories, 1 file
```
> chore(mark): remove election from `localStorage`

- Procfile
- RustConfig
Ideally these would live in services/rave-server but this is functional for now. There are buildpacks you can link with the rust one I am using to specify a path to the Procfile with an env variable so that one is easy, but the rust buildpack only knows to look in the root for its RustConfig file which you need to specify the path for the Cargo.toml. Longer term you could easily fork the rust buildpack and modify it to solve that problem though. 
FYI that there are various ROCKET_ environment variables set in the heroku dashboard and the configuration using the rusk buildpack (https://github.com/emk/heroku-buildpack-rust) is there as well.
> Set up config for heroku deploy of rave server

- apps/rave-jx-terminal/frontend/public/styles.css
- apps/rave-mark/frontend/src/screens/voter_flow_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/already_voted_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/index.tsx
- apps/rave-mark/frontend/src/screens/voting/post_vote_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/submit_screen.tsx
The mailing label will likely require data from the sign & cast operation, so this commit moves that step to the end. This change also allows us to more easily distinguish the "just voted" from "previously voted" states, so we can show more specific instructions for those cases.
Also:
- remove voter-facing mentions of "signing"
- use unicode instead of `&rsquo;`
- minor visual tweaks: `padded` and `H2` instead of `H1`
**Note:** there is a [known issue](https://votingworks.slack.com/archives/CEL6D3GAD/p1693956894994539) with this where the size of the `@page` is not respected for some subsequent print-to-PDF requests. I'm not sure why, but I'm going to merge this anyway since I plan to change the approach for building the label and I'd rather just land this first. …
> feat(rave-mark): print the mailing label last

- script/rave-setup
It provides the `lpr` command we use in `rave-mark`.
n/a
Manual.
> build: install `cups-bsd` during setup

- apps/rave-mark/backend/src/app.ts
- apps/rave-mark/frontend/jest.config.js
- apps/rave-mark/frontend/package.json
- apps/rave-mark/frontend/src/components/pin_pad_modal.test.tsx
- apps/rave-mark/frontend/src/components/pin_pad_modal.tsx
- apps/rave-mark/frontend/src/screens/registration/start_screen.tsx
- apps/rave-mark/frontend/src/screens/voting/submit_screen.tsx
- apps/rave-mark/frontend/test/setup.ts
- libs/auth/src/apdu.ts
- libs/auth/src/java_card.ts
- libs/auth/src/piv.ts
- libs/basics/src/errors.test.ts
- libs/basics/src/errors.ts
- pnpm-lock.yaml
When we moved the PIN check to the end of the voting flow we lost the PIN check for registration. This adds that back at the end on submit, just like with voting. We don't use it to sign anything yet, but that'll come later.
https://github.com/votingworks/rave/assets/1938/3188c3a0-7d86-4e61-a773-433c155abadf
Manual, but with an automated test for the new `PinPadModal`.
> feat(rave-mark): check PIN on registration

- apps/rave-mark/backend/src/app.ts
- apps/rave-mark/backend/src/rave_server_client.ts
- apps/rave-mark/backend/src/store.ts
- apps/rave-mark/frontend/src/api.ts
- apps/rave-mark/frontend/src/screens/admin/dashboard_screen.tsx
Adds synced/pending count table to the Admin dashboard. Also fixes a couple issues:
- admin lookup was incorrect (swapped CAC ID & machine ID)
- scanned ballots were not being persisted in the mark DB
Manually tested with my sample CAC card made into an admin user.
> feat(rave-mark): add more sync status to Admin dashboard

- apps/cacvote-jx-terminal/backend/src/config.rs
- apps/cacvote-jx-terminal/frontend/package.json
- apps/cacvote-mark/backend/.env
- apps/cacvote-scan/backend/.env
- apps/cacvote-scan/backend/src/config.rs
- pnpm-lock.yaml
The rename from RAVE to CACVote messed up the environment variable name. Also, I removed the `package.json` for `jx/backend` since it's not a node package, but the frontend was depending its `package.json` scripts.
> fix(jx): make running work properly

- libs/auth-rs/examples/read_card_status.rs
- libs/auth-rs/src/card_command.rs
- libs/auth-rs/src/card_reader.rs
- libs/auth-rs/src/command_apdu.rs
- libs/auth-rs/src/hex_debug.rs
- libs/auth-rs/src/lib.rs
We were previously sending an extra byte for the length, but that's not how those commands work. This also adds some basic `tracing` logging that I used to figure out the bug.
> fix(auth-rs): correctly send "get response" commands

- Cargo.lock
- libs/auth-rs/src/lib.rs
- libs/types-rs/Cargo.toml
- libs/types-rs/src/cacvote/mod.rs
- services/cacvote-server/Cargo.toml
- services/cacvote-server/src/app.rs
- services/cacvote-server/src/client.rs
- services/cacvote-server/src/db.rs
Uses OpenSSL to verify the signature for the payload based on the provided certificate. It doesn't yet verify the certificate itself.
> feat: verify signature of object payload

- apps/cacvote-jx-terminal/frontend/Cargo.toml
- libs/ui-rs/Cargo.toml
That's the version that we're including anyway (notice `Cargo.lock` doesn't change). Any installation of `dioxus-cli` is going to include 0.2.92 and the versions have to match, so this just makes things a bit less confusing.
> build: reference `wasm-bindgen` 0.2.92

- libs/auth/src/java_card.ts
Rather than hardcoding a fixed number of bytes to trim we now properly parse the nested response TLV structures. While the old way didn't bite us in practice, if the signature returned was ever larger than 0x80 bytes the TLV would use two bytes to encode the length and the signature would be corrupted.
n/a
Automated tests, plus manual testing with a sysadmin card.
> fix(auth): properly parse the challenge response

- Cargo.lock
- Cargo.toml
- apps/cacvote-jx-terminal/backend/Cargo.toml
- apps/cacvote-jx-terminal/backend/src/app.rs
- apps/cacvote-jx-terminal/backend/src/db.rs
- apps/cacvote-jx-terminal/backend/src/smartcard.rs
- apps/cacvote-jx-terminal/frontend/src/layouts/app_layout.rs
- apps/cacvote-jx-terminal/frontend/src/pages/elections_page.rs
- libs/types-rs/src/cacvote/mod.rs
Replaces `try_stream!` with a broadcast stream. This means that no matter how many requests we get for the status stream endpoint we only collect the data for it in one place. Previously, the loop inside the `try_stream!` would run even after the connection was closed, resulting in excess resource usage.
> fix(jx): improve reliability of smartcard detection and status stream

- mprocs.yaml
Since I added another binary we can't just do `cargo run` anymore, we have to specify which binary we want to run. This required changing the style for the `cargo watch` invocation, so I also changed it for `cacvote-server` just to be consistent.
> fix(mprocs): specify the binary for JX backend

- apps/cacvote-jx-terminal/backend/src/db.rs
- apps/cacvote-jx-terminal/frontend/src/app_root.tsx
- apps/cacvote-jx-terminal/frontend/src/cacvote-server/session_data.ts
- apps/cacvote-jx-terminal/frontend/src/components/create_election_modal.tsx
- apps/cacvote-jx-terminal/frontend/src/components/date_time_cell.tsx
- apps/cacvote-jx-terminal/frontend/src/components/election_card.tsx
- apps/cacvote-jx-terminal/frontend/src/components/registration_configuration_cell.tsx
- apps/cacvote-jx-terminal/frontend/src/components/voter_info_cell.tsx
- apps/cacvote-jx-terminal/frontend/src/screens/election_screen.tsx
- apps/cacvote-jx-terminal/frontend/src/screens/elections_screen.tsx
- apps/cacvote-jx-terminal/frontend/src/screens/navigation_screen.tsx
- apps/cacvote-jx-terminal/frontend/src/screens/tally_screen.tsx
- apps/cacvote-jx-terminal/frontend/src/screens/voters_screen.tsx
- libs/types-rs/src/cacvote/mod.rs
The tally screen is just a placeholder for now.
> feat(jx): add election screens (info, tally)

- Cargo.lock
- Cargo.toml
- apps/cacvote-mark/backend/src/app.ts
- apps/cacvote-mark/backend/src/electionguard.ts
- apps/cacvote-mark/frontend/package.json
- apps/cacvote-mark/frontend/src/random.test.ts
- apps/cacvote-mark/frontend/src/random.ts
- apps/cacvote-mark/frontend/src/screens/voter_flow_screen.tsx
- apps/cacvote-mark/frontend/src/screens/voting/submit_screen.tsx
- libs/electionguard-rs/Cargo.toml
- libs/electionguard-rs/src/ballot.rs
- libs/electionguard-rs/src/mixnet.rs
- libs/electionguard/index.test.ts
- libs/electionguard/napi.d.ts
- libs/electionguard/src/lib.rs
- pnpm-lock.yaml
Changes the ElectionGuard API to require passing a serial number, which is now generated on the frontend.
> feat(mark): print serial number on ballot

- apps/cacvote-mark/backend/src/app.ts
- apps/cacvote-mark/backend/src/verification.test.ts
- apps/cacvote-mark/backend/src/verification.ts
- Use binary UUID encoding
- Add `machineId` to the ballot verification payload
> feat(mark): QR code updates

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- libs/tlv-derive/Cargo.toml
- libs/tlv-derive/README.md
- libs/tlv-derive/src/lib.rs
- libs/tlv-derive/tests/integration_tests.rs
- libs/tlv/Cargo.toml
- libs/tlv/src/coder.rs
- libs/tlv/src/error.rs
- libs/tlv/src/length.rs
- libs/tlv/src/lib.rs
- libs/tlv/src/limited_reader.rs
- libs/tlv/src/tag.rs
- libs/tlv/src/value.rs
These libraries provide TLV encode/decode functionality.
An example of `derive`ing `tlv::Decode` and `tlv::Encode` and basic usage:
```rust
#[derive(tlv::Decode, tlv::Encode)]
struct Test {
#[tlv(tag = 0x20)]
a: u8,
#[tlv(tag = 0x21)]
b: u16,
}
let value = Test { a: 0, b: 999 };
let encoded = tlv::to_vec(&value)?;
let decoded: Test = tlv::from_slice(&encoded)?;
```
This is what the derive macros actually expand to (courtesy of `cargo expand`):
```rust
use tlv::Encode;
use tlv_derive::{Decode, Encode};
struct Test {
#[tlv(tag = 0x20)]
a: u8,
#[tlv(tag = 0x21)]
b: u16,
}
impl tlv::Encode for Test {
fn encode<W>(&self, writer: &mut W) -> std::io::Result<()>
where
W: std::io::Write,
{
tlv::value::encode_tagged(tlv::Tag::U8(32u8), &self.a, writer)?; …
```
> feat(libs): add `tlv` and `tlv-derive` libs

- apps/cacvote-mark/backend/src/cacvote-server/usability_test_client.test.ts
- apps/cacvote-mark/backend/src/cacvote-server/usability_test_client.ts
- apps/cacvote-mark/backend/src/env.d.ts
- apps/cacvote-mark/backend/src/globals.ts
- apps/cacvote-mark/backend/src/server.ts
- mprocs-usability-test.yaml
Sounds like they want to do the registration upfront and then only test the voting flow, so make the default expiration be `castBallotOnly`.
> feat(mark): allow configuring what to expire in the usability test

- apps/cacvote-mark/frontend/src/components/remove_common_access_card_icon.tsx
There was a gray top border on the original image for some reason. This fixes the glitch by replacing the SVG that is actually just an embedded PNG with a real SVG.
| Before | After |
|-|-|
|![localhost_64113_](https://github.com/votingworks/cacvote/assets/1938/b1077c5a-ab0a-4688-8352-0337b9387ff4)|![localhost_64113_ (1)](https://github.com/votingworks/cacvote/assets/1938/02b376d9-d408-4e24-b8d0-1337d6fbb8c0)|
> fix(mark): correct graphical glitch on "remove card" icon

- apps/cacvote-jx-terminal/backend/bin/decrypt-tally.rs
- apps/cacvote-jx-terminal/backend/src/app.rs
- libs/types-rs/src/cacvote/mod.rs
This was broken because we weren't properly handling the encrypted ballot data as a base64-encoded string. Without this, the tally would succeed but be wrong and the mixnet shuffle would fail.
> fix(jx): make tallies work again

- README.md
- script/cacvote-setup
- install `sqlite3` so it can be used by the `reset-db` process in `mprocs` configs
- build the `electionguard` Rust addon on setup
- add instructions to program the cards needed for testing
- add instructions for printing to PDF
> build: various fixes

- apps/cacvote-server/backend/Makefile
Simple pathing update due to restructuring that moved `cacvote-server` from the old `services` pattern to the `apps/backend|frontend` pattern.
> pathing has changed since moving server from services to apps structure

- libs/auth-rs/src/vx_card.rs
- libs/auth/scripts/create_production_machine_cert_signing_request.ts
- libs/auth/src/certs.ts
- libs/auth/src/config.ts
- libs/auth/src/env.d.ts
- libs/auth/src/java_card.ts
This PR accounts for the new CACvote machine types in `libs/auth` and `libs/auth-rs`, specifically making it such that 1) sys admin card bootstrapping in the `cacvote-jx-terminal` machine configuration wizard will work and 2) cards generated via that process will be accepted by the `cacvote-jx-terminal`.
I don't have a great test environment ready to go and need to shift back to other threads but am happy to address any errors that arise in testing!
> Account for new CACvote machine types in libs/auth and libs/auth-rs

- Aptfile
Just a quick test of using the apt buildpack to install libpcsclite packages.
> using apt buildpack to install libpcsclite

- apps/cacvote-server/backend/script/build
Disabling SQLX_OFFLINE to test the heroku build. Even if this succeeds, it may not be the optimal solution for all other builds.
> test disabling SQLX_OFFLINE

- apps/cacvote-jx-terminal/frontend/package.json
- apps/cacvote-jx-terminal/frontend/src/components/create_election_modal.tsx
- apps/cacvote-jx-terminal/frontend/src/screens/tally_screen.tsx
- apps/cacvote-jx-terminal/frontend/src/utils/download.ts
- mprocs-cacvote-jx-terminal.yaml
- mprocs-cacvote-mark.yaml
- pnpm-lock.yaml
When running in `kiosk-browser` we use its extensions to make interacting with the file system easier.
> feat(jx): use `kiosk` open/save dialogs for file IO

- apps/cacvote-jx-terminal/backend/src/app.rs
- apps/cacvote-jx-terminal/frontend/src/api.ts
- apps/cacvote-jx-terminal/frontend/src/screens/tally_screen.tsx
- apps/cacvote-server/backend/src/app.rs
- apps/cacvote-server/backend/src/db.rs
- apps/cacvote-server/frontend/src/api.ts
- apps/cacvote-server/frontend/src/screens/search_screen.tsx
- libs/types-rs/src/cacvote/mod.rs
Adds the `/api/elections/{election_id}/scanned-mailing-labels` endpoint to the JX terminal backend in order to proxy it to `cacvote-server`.
> feat(jx): download ballot manifest from election tally page

- apps/cacvote-jx-terminal/backend/src/session_manager.rs
Previously, you'd just stay logged in. I'd assumed that if the card reader was removed that we'd also get a `CardRemoved` event, because this is how it works when you plug the card reader in (you get both `ReaderAdded` and `CardInserted`). However, this is not the case. This change ensures that we log the user out when the reader is removed. At this time, we assume a single reader.
> fix(jx): log out on card reader removal

- apps/cacvote-jx-terminal/frontend/src/api.ts
- apps/cacvote-jx-terminal/frontend/src/app_root.tsx
- apps/cacvote-jx-terminal/frontend/src/components/pin_pad_modal.tsx
Currently, we're throwing an error which just causes the "Something Went Wrong" screen to appear. This changes that to show a (hardcoded) error instead. Also fixes the flicker that shows the "Insert Card Screen" while checking the PIN.
> fix(jx): show error on invalid PIN

- README.md
This was removed because we’re now just using the signed certificate to verify the payload of the mailing label QR code.
> docs: remove reference to outdated script

- apps/cacvote-mark/backend/src/bin/test-print-mail-label/main.ts
- apps/cacvote-mark/backend/src/mail-label/nprint/client.ts
- apps/cacvote-mark/backend/src/mail-label/nprint/types.ts
- apps/cacvote-mark/backend/src/mail-label/printing.ts
- apps/cacvote-mark/backend/src/mail-label/rendering/index.tsx
- apps/cacvote-mark/nprint/src/main.rs
- apps/cacvote-mark/nprint/src/nprint.rs
- script/cacvote-setup
There are a few problems with the old setup:
1. We didn't have any way of granting permissions to the printer to the current user (fixed with udev config and `lp` group membership).
2. We didn't install the playwright chromium browser for rendering the label (fixed by triggering the install on setup).
3. We didn't install the shared object correctly so it would either fail the `nprint` build or fail to be loaded at runtime.
4. We didn't ever enumerate the label printers before trying to connect, but per the docs we need to do that or `libNPrint` cannot establish a connection at all.
> build(mark): fix setup for the label printer
